### ISSUE TITLE
Click event listener for action component is fired twice when clicked.

### ISSUE THREAD

**Issue by ptychu** [wizdmio/wizdm#12]
When clicking 'save' action in profile component updateProfile() is executed twice. Additionally updateProfile() is executed even if action is disabled.

Tested on:
Linux: Chrome 81.0.4044.129 (Official Build) (64-bit).

**Comment by lasfrancisco** [comment]
This is an issue of the wm-action component, so, I'd expect to see the same behavior wherever it has been used. Since there's no effective way to prevent the click event to propagate I'm going to rename the wm-action event from 'click' to 'activate. Being a breaking change all the binding around the app will require to be updated

**Comment by ptychu** [comment]
@lasfrancisco What do you mean by 'no effective way to prevent click event to propagate'? Is there a reason why `pointer-events: none` style is a bad solution?

**Comment by lasfrancisco** [comment]
I didn't consider using `pointer-events: none`, actually. What I meant is that according to Angular design, there's not a reliable way for a sibling event handler to catch an event and to stop propagating it so for the other handlers to never receive the event (it works from children to parent though). 
The issue you reported is due to the fact wm-action emits a 'click' event programmatically when one of the contained buttons is clicked but it also emits a 'click' wherever and whenever the component is clicked onto by the Element click event handler. The latter cannot reliably be prevented by the former. 
By using  `pointer-events: none` as you suggest we'll block all the click events, so, the buttons within the wm-action component won't get clicked as well. Enabling pointer-events back for the contained buttons will turn both click events back on again.
That's why a believe the cleaner solution is to call the wm-action activation event something different from 'click'.

**Comment by ptychu** [comment]
I like action being fired by a click, and disabled with `disabled`. I feel like it provides intuitive interface. I may be wrong about this being the best solution though...

That being said I think we can make it work:
1. `pointer-events: none` stops event during capture phase. This means button will not receive click even when action is disabled. This fixes disabled for action component.
2. It is not need to fire click event from action component. We just register a listener to the button (here action bar is notified). Then during bubbling click event of action component is triggered. This way event listener is triggered only once.

I updated my PR accordingly. 
It works fine on profile component. I didn't find any other meaningful use of wm-action (folder component and apply component seem not to be in use yet).

**Comment by lasfrancisco** [comment]
I loved the idea to use `click` as well but after some testing, I'm now concerned about the best way to go. I'll be looking into your pull request. Be aware that your modifications turned the component from ViewEncapsulation.None (since there was no styling at all) to ViewEncapsulation.Emulated, so, you may want to take a look at that. Besides, the component design choice of containing two different types of mat-button never excited me much, so, we may want to go for a more radical solution by redesigning the overall component as a single button having the click event solved like a cherry on top of the cake. 
Meanwhile, I took the short way by switching to 'activate' event.

**Comment by lasfrancisco** [comment]
Closed by merging #13. Nice work. Please take a look to the button-change directive and let me know what you think about it.
