### ISSUE TITLE
Parameters within routes

### ISSUE THREAD

**Issue by ptychu** [wizdmio/wizdm#17]
Hi @lasfrancisco,

I'm trying to a relatively simple thing: trying to add my own form like component that would allow to edit particular database entry. I'm struggling to understand how to properly set up routing. I've tried adding `my-component/:id` route, but it fails, as it tries to resolve `assets/docs/en/my-component/<:id>.md`

I tried to read the docs you recently wrote and analyse how wizdm routing works, but I'm still struggling to understand how to achieve my goal. I'd love to keep implemented features, like resolving `assets/i18n/<language>/my-component.json`.

Do you have any suggestions on how to approach my problem, or where to begin?

**Comment by lasfrancisco** [comment]
Hi there. It seems to me you're trying to add a page copying the StaticModule that uses a peculiar content resolver. That's the only reason I can think of to get your module trying to resolve a file from assets/docs.

To add a page of your's I'd recommend cloning one of the others (home, features, profile...) that uses the ContentRouterModule to install content resolvers at run-time.

Write directly to hello@widm.io for further assistance instead of opening issues unless you're facing a bug or requesting a feature improvement. Thx
