### ISSUE TITLE
module - Consider changing the function expression into an exported function

### ISSUE THREAD

**Issue by peterpullmann** [wizdmio/wizdm#35]
Hi,
thank you very much for fantastic job.
Please I have issue on versions:
Angular: 9.1.12
Angular CLI: 9.1.6
Node: 12.19.0
Npm: 6.14.6

ERROR in Error during template compile of 'AppModule'
  Function expressions are not supported in decorators in 'PayPalModule'
    'PayPalModule' contains the error at app/_services/paypal/paypal.module.ts(19,23)
      Consider changing the function expression into an exported function.

I have a problem with this row:
 { provide: PAYPAL_INSTANCE, useFactory: () => PayPalModule._paypal }

Please could you help me, how to write it differently?

Thanks a lot.
Regards.
Peter

**Comment by lasfrancisco** [comment]
Hi Peter, thank you for your feedback. I assume you are compiling your project having Ivy disabled since this was a common error with the AOT compiler of the ViewEngine.

Possible solutions are:
1. enable Ivy, so, your app will be compiled with the new AOT compiler.
1. move the factory code into an exported function (avoiding to use the arrow function) and use that function within the decorator. You'll be needing to switch the _paypal variable into `public`.

```typescript

export function PayPalInstance() {
 return PayPalModule._paypal;
}

```

If you can update to ng10, you may consider using `@wizdm/paypal` as a module instead.

Finally, you may consider contributing to the project, we are always looking for new enthusiastic members to join.
Lucio
