### ISSUE TITLE
 Error: Cannot assign value "$event" to template variable "menu". Template variables are read-only.

### ISSUE THREAD

**Issue by mtabaj** [wizdmio/wizdm#7]
Hi, I'm trying to use the last version of wizdm with angular 9 RC3, and I get the following error:

**Cannot assign value "$event" to template variable "menu". Template variables are read-only.**

Can you tell me please where it happens and how to fix it ?
Thanks in advance,
Marcos

**Comment by lasfrancisco** [comment]
Yeah right, I see the error. I feel I already fixed it locally but couldn’t commit since modifications are in progress. Here the piece of code from navigator.component.html:


<mat-toolbar-row auto *ngIf="mobile && msgs.menu as menu">

<wm-menu [menuItems]="signedIn ? menu.private : menu.public" [toggle]=" toggler" (visible)="menu = $event"></wm-menu>
</mat-toolbar-row>

Change the name of the template variable within the ngIf=“... as menu” to something different like ‘mob’. Then refer to the following inline conditional assignment to ‘mob’ instead of ‘menu’ but keep assigning the $event to ‘menu’ as now.

**Comment by lasfrancisco** [comment]
The fix has been included in the new release

**Comment by WuMianRen** [comment]
ERROR in Error: Cannot assign value "$event" to template variable "point". Template variables are read-only. ???

**Comment by lasfrancisco** [comment]
Hi there, if you're still experiencing this issue, I'd recommend pulling the latest version
